name: Generate contributors

on:
  workflow_dispatch:
    inputs:
      excludeBot:
        description: "Exclude actions@github.com from contributors"
        required: false
        type: boolean
        default: false
      notGenerateContributorsMd:
        required: false
        type: boolean
        default: false
        description: "Not commit CONTRIBUTORS.md ?"
      commitMessageBot:
        required: true
        type: string
        default: "[Update] Automate update contributors"
        description: "Commit message which bot will do"

  schedule:
    - cron: '0 0 * * 1'
  pull_request:
    types: [ opened, synchronize, edited ]
  push:
    branches:
      - master
      - main
      - develop
      - feature/**
      - release/**
      - test/**
      - bugfix/**

jobs:
  generate-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Generate contributors
        uses: gouef/create-contributors-action@main
        with:
          excludeBot: ${{ inputs.excludeBot || false}}
          notGenerateContributorsMd: ${{ inputs.notGenerateContributorsMd || false }}
          commitMessageBot: ${{ inputs.commitMessageBot }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
